version: "3.9"
services:
  futu-grid-trading:
    image: futu-grid-trading
    build: .
    network_mode: "host"
    container_name: futu-grid-trading
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment: 
      - PWD_UNLOCK=$PWD_UNLOCK
      - LOG_LEVEL=$LOG_LEVEL
      - DRY_RUN=$DRY_RUN
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./vol/log:/var/log/futu-grid-trading
      - ./vol/prod.config.yml:/vol/prod.config.yml
    command: python3 /opt/futu-grid-trading/main.py -c /vol/prod.config.yml
